### ISSUE TITLE
lib/axios/index.ts error

### ISSUE THREAD

**Issue by azumukupoe** [screeny05/letterboxd-list-radarr#23]
```
[nodemon] app crashed - waiting for file changes before starting...

Debugger listening on ws://127.0.0.1:5858/3560c134-622a-4585-81fd-abe2dd1fcfff

For help, see: https://nodejs.org/en/docs/inspector


/home/node/app/node_modules/ts-node/src/index.ts:500

    return new TSError(diagnosticText, diagnosticCodes)

           ^

TSError: ⨯ Unable to compile TypeScript:

lib/axios/index.ts(7,35): error TS1109: Expression expected.

lib/axios/index.ts(7,47): error TS1005: ':' expected.

lib/axios/index.ts(8,58): error TS1109: Expression expected.

lib/axios/index.ts(8,63): error TS1005: ':' expected.

lib/axios/index.ts(8,72): error TS1109: Expression expected.

lib/axios/index.ts(8,80): error TS1005: ':' expected.

lib/axios/index.ts(8,91): error TS1109: Expression expected.

lib/axios/index.ts(8,100): error TS1005: ':' expected.


    at createTSError (/home/node/app/node_modules/ts-node/src/index.ts:500:12)

    at reportTSError (/home/node/app/node_modules/ts-node/src/index.ts:504:19)

    at getOutput (/home/node/app/node_modules/ts-node/src/index.ts:942:34)

    at Object.compile (/home/node/app/node_modules/ts-node/src/index.ts:955:32)

    at Module.m._compile (/home/node/app/node_modules/ts-node/src/index.ts:1043:43)

    at Module._extensions..js (node:internal/modules/cjs/loader:1131:10)

    at Object.require.extensions.<computed> [as .ts] (/home/node/app/node_modules/ts-node/src/index.ts:1046:12)

    at Module.load (node:internal/modules/cjs/loader:967:32)

    at Function.Module._load (node:internal/modules/cjs/loader:807:14)

    at Module.require (node:internal/modules/cjs/loader:991:19)

npm ERR! code 1

npm ERR! path /home/node/app

npm ERR! command failed

npm ERR! command sh -c node --inspect=5858 -r ts-node/register/transpile-only index.ts


npm ERR! A complete log of this run can be found in:

npm ERR!     /home/node/.npm/_logs/2022-03-09T07_21_14_527Z-debug.log
```
```
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/node/app/.npmrc Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/node/.npmrc Completed in 0ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session 15e97914a7aff938
20 timing npm:load Completed in 21ms
21 http fetch GET 200 https://registry.npmjs.org/npm 252ms
22 timing command:run-script Completed in 6127ms
23 verbose stack Error: command failed
23 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
23 verbose stack     at ChildProcess.emit (node:events:376:20)
23 verbose stack     at maybeClose (node:internal/child_process:1055:16)
23 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
24 verbose pkgid letterboxd-list-radarr@1.0.1
25 verbose cwd /home/node/app
26 verbose Linux 5.10.60.1-microsoft-standard-WSL2
27 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
28 verbose node v15.3.0
29 verbose npm  v7.0.14
30 error code 1
31 error path /home/node/app
32 error command failed
33 error command sh -c node --inspect=5858 -r ts-node/register/transpile-only index.ts
34 verbose exit 1

```

**Comment by screeny05** [comment]
It seems like typescript does not recognize the optional chaining in this file.

Can you provide  me with steps to reproduce this issue? Following the README on macOS does not give me this error.

Also, please provide me with the output of both `npm list` and `npm list --dev`

Thank you.

**Comment by azumukupoe** [comment]
I'm running Docker on Windows 11

`npm list`
```
letterboxd-list-radarr@1.0.1 /home/node/app
+-- @types/express@4.16.1
+-- @types/node@12.0.2
+-- @types/redis@2.8.12
+-- @types/winston@2.4.4
+-- axios@0.18.1
+-- express@4.17.1
+-- kanpai-scraper@0.1.0
+-- nodemon@2.0.6
+-- p-limit@2.2.0
+-- UNMET DEPENDENCY read-pkg-up@^7.0.1
+-- redis@2.8.0
+-- UNMET DEPENDENCY robots-parser@^2.3.0 deduped
+-- ts-node@9.0.0 invalid
+-- typescript@3.4.5 invalid
`-- winston@3.3.3

npm ERR! code ELSPROBLEMS
npm ERR! missing: read-pkg-up@^7.0.1, required by letterboxd-list-radarr@1.0.1
npm ERR! missing: robots-parser@^2.3.0, required by letterboxd-list-radarr@1.0.1
npm ERR! invalid: ts-node@9.0.0 /home/node/app/node_modules/ts-node
npm ERR! invalid: typescript@3.4.5 /home/node/app/node_modules/typescript

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-03-14T11_58_26_259Z-debug.log
```
```
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'list' ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/node/app/.npmrc Completed in 0ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/node/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 63a7da8c42cc8913
20 timing npm:load Completed in 19ms
21 http fetch GET 200 https://registry.npmjs.org/npm 228ms
22 timing arborist:ctor Completed in 1ms
23 timing command:ls Completed in 654ms
24 verbose stack Error: missing: read-pkg-up@^7.0.1, required by letterboxd-list-radarr@1.0.1
24 verbose stack missing: robots-parser@^2.3.0, required by letterboxd-list-radarr@1.0.1
24 verbose stack invalid: ts-node@9.0.0 /home/node/app/node_modules/ts-node
24 verbose stack invalid: typescript@3.4.5 /home/node/app/node_modules/typescript
24 verbose stack     at ls (/usr/local/lib/node_modules/npm/lib/ls.js:491:7)
25 verbose cwd /home/node/app
26 verbose Linux 5.10.60.1-microsoft-standard-WSL2
27 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "list"
28 verbose node v15.3.0
29 verbose npm  v7.0.14
30 error code ELSPROBLEMS
31 error missing: read-pkg-up@^7.0.1, required by letterboxd-list-radarr@1.0.1
31 error missing: robots-parser@^2.3.0, required by letterboxd-list-radarr@1.0.1
31 error invalid: ts-node@9.0.0 /home/node/app/node_modules/ts-node
31 error invalid: typescript@3.4.5 /home/node/app/node_modules/typescript
32 verbose exit 1
```
`npm list --dev`
```
letterboxd-list-radarr@1.0.1 /home/node/app
+-- @types/express@4.16.1
+-- @types/node@12.0.2
+-- @types/redis@2.8.12
+-- nodemon@2.0.6
`-- ts-node@9.0.0 invalid

npm ERR! code ELSPROBLEMS
npm ERR! invalid: ts-node@9.0.0 /home/node/app/node_modules/ts-node

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-03-14T11_59_57_834Z-debug.log
```
```
0 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'list', '--dev' ]
1 info using npm@7.0.14
2 info using node@v15.3.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 0ms
5 timing config:load:builtin Completed in 0ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/node/app/.npmrc Completed in 1ms
9 timing config:load:project Completed in 2ms
10 timing config:load:file:/home/node/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session 7521477ebe97bac3
20 timing npm:load Completed in 17ms
21 http fetch GET 200 https://registry.npmjs.org/npm 349ms
22 timing arborist:ctor Completed in 1ms
23 timing command:ls Completed in 726ms
24 verbose stack Error: invalid: ts-node@9.0.0 /home/node/app/node_modules/ts-node
24 verbose stack     at ls (/usr/local/lib/node_modules/npm/lib/ls.js:491:7)
25 verbose cwd /home/node/app
26 verbose Linux 5.10.60.1-microsoft-standard-WSL2
27 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "list" "--dev"
28 verbose node v15.3.0
29 verbose npm  v7.0.14
30 error code ELSPROBLEMS
31 error invalid: ts-node@9.0.0 /home/node/app/node_modules/ts-node
32 verbose exit 1

```

**Comment by screeny05** [comment]
You'll need to re-run `npm install`. You are using outdated packages.

I'll close this issue, as that should fix the problem.

If you have any further questions or this didn't solve the problem, please feel free to comment here.

**Comment by screeny05** [comment]
(The dependencies have been bumped with commit [2fd1f21](https://github.com/screeny05/letterboxd-list-radarr/commit/2fd1f21c26869fd6fbc3c9f0203171563a97aecf#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519))
